### PR TITLE
Feature/fetching tokens

### PR DESCRIPTION
**Pull request by mpetrunic**

### CODE REVIEW

**Comment by morrigan** [comment]
@mpetrunic from where does web read those tokens? I guess javascript so it will be hard to replace

**Comment by mpetrunic** [comment]
Web is currently reading from `main.json`, from now on it should read from this endpoint. The data format is the same.

**Comment by morrigan** [comment]
When merged, change the frontend to:
 - fetch this instead of `main.json` (find `configName`)
 - fetch this instead of `tokenGuides` folder (find `/tokenGuides/` or tokenName in main.js)

Token model should have `description` and `url` also

**Comment by mpetrunic** [comment]
There should be another api that returns json object same as in main.json

**Review by morrigan — APPROVED** [review]

**Pull request merged**
